---
- name: Gets installed Tmux version
  shell: tmux -V > /dev/null 2>&1 && tmux -V | cut -f2 -d ' ' || echo 0.0
  register: __tmux_version
  changed_when: false
  always_run: yes

- debug: 
    msg: "Detected tmux version {{ __tmux_version }}"
  when: __tmux_version is defined and __tmux_version.stdout is defined

- name: Adds .tmux.conf for all accounts for detected version
  template: 
    src: '../templates/tmux.conf.j2' 
    dest: "~{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: tmux_users
  when: __tmux_version is defined and __tmux_version.stdout is defined

